spring.application.name=cashr.api
server.port=8080

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/cashr
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=your-very-very-long-secret-key-minimum-32-characters-never-share-this-key
jwt.expiration=86400000
